[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT config.wsgi:application --workers 3 --threads 2 --timeout 120"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
